### ISSUE TITLE
What is the point of this interval?

### ISSUE THREAD

**Issue by alexdunk** [openai/openai-assistants-quickstart#23]
This is the solution to fetching files after uploading/deleting or am I missing something? 
Why not call fetchFiles after uploading and deleting?

```
useEffect(() => {
    const interval = setInterval(() => {
      fetchFiles();
    }, 1000);

    return () => clearInterval(interval);
  }, []);
```

``` 
const fetchFiles = async () => {
    const resp = await fetch("/api/assistants/files", {
      method: "GET",
    });
    const data = await resp.json();
    setFiles(data);
  };
```

**Comment by athrael-soju** [comment]
Quickly! Close this issue before someone sees it!

All kidding aside, this is just a quickstart example. I would suggest you use it as a stepping stone to understanding how assistants work internally, but otherwise don't focus too much on the coding practices.

**Comment by alexdunk** [comment]
okay fair lol
