### ISSUE TITLE
Stuck and Task timeout with longer responses

### ISSUE THREAD

**Issue by andreavigani** [openai/openai-assistants-quickstart#24]
I deployed it on Netlify setting up my assistant but I noticed that when the response is a bit longer it get stuck, it truncate response and send button is disabled, need to refresh page.

Jun 8, 12:12:43 AM: 00634a06 ERROR  Task timed out after 10.03 seconds
Jun 8, 12:12:43 AM: 00634a06 Duration: 10031.32 ms	Memory Usage: 85 MB

Also the sources in the responses are not formatted correctly:【7:3†source】【7:10†source

**Comment by andreavigani** [comment]
increase timeout functions via netlify support

**Comment by jctackett** [comment]
I am having the same issue; what was the resolution?
