### ISSUE TITLE
Feedback form not public

### ISSUE THREAD

**Issue by Defimatt** [openai/openai-assistants-quickstart#3]
> Feedback
> Let us know if you have any thoughts, questions, or feedback in [this form](https://docs.google.com/forms/d/e/1FAIpQLSdquOq8U8cvqL4EVCXuJ3oPag2w7KySsC0PLxv6VAHon6smrw/viewform?usp=sf_link)!

Visiting form link gives:

> You need permission
> This form can only be viewed by users in the owner's organisation.
> 
> Try contacting the owner of the form if you think that this is a mistake.

**Comment by ibigio** [comment]
Fixed! Thanks for pointing this out.
