### ISSUE TITLE
When I send messages there's  error shows

### ISSUE THREAD

**Issue by aaaa-zhen** [openai/openai-assistants-quickstart#9]
<img width="972" alt="image" src="https://github.com/openai/openai-assistants-quickstart/assets/43779067/b2f92325-b61b-4f64-9e75-0d5fae6f4f61">

**Comment by zhongerxin** [comment]
me too
Error: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by divofred** [comment]
I think the problem comes from the assistant ID being null or invalid

**Comment by yt3trees** [comment]
I had the same error, but I solved it by setting the API key to .env instead of setting it to an environment variable.

**Comment by aaaa-zhen** [comment]
> I think the problem comes from the assistant ID being null or invalid

yes,you're right fixed. thanks

**Comment by aaaa-zhen** [comment]
yes,you're right fixed. thanks
